### ISSUE TITLE
Federation issues with following users on Friendica and Pixelfed instances

### ISSUE THREAD

**Issue by mgrzeca** [VernissageApp/VernissageServer#136]
I’m experiencing problems with federation. I can search for users from other instances, but following them only works reliably with Mastodon- and Vernissage-based servers.

When trying to follow users on Friendica or Pixelfed, the behavior is similar to what was described in issue #32 back in early April. Below is a sample log:

```
vernissage-api  | [ INFO ] GET /api/v1/search [request-id: 46570FDF-A263-4173-BC0C-11FDF1932081]
vernissage-api  | [ INFO ] GET /api/v1/relationships [request-id: B2FFB813-EF65-45B9-988D-41B0D5E47B00]
vernissage-api  | [ INFO ] GET /api/v1/users/@z428@loma.ml [request-id: 03567765-3EE4-4DA3-84CA-6A131C34C40E]
vernissage-api  | [ INFO ] GET /api/v1/users/@z428@loma.ml/followers [request-id: AD4E2AAC-9692-404F-ACF1-3A67AD2491D2]
vernissage-api  | [ INFO ] GET /api/v1/relationships [request-id: 9ED2EE33-3BF3-47CC-9191-CD9899C5096C]
vernissage-api  | [ INFO ] GET /api/v1/users/@z428@loma.ml/statuses [request-id: 9E535321-D810-4D4B-86B9-35F081643791]
vernissage-api  | [ INFO ] POST /api/v1/users/@z428@loma.ml/follow [request-id: D870E4CB-E308-471D-A90B-4A0A92C90B47]
vernissage-api  | [ INFO ] Dispatched job [job-id: FC8A0C41-5F54-45AA-BBD2-09865B6944CE, job-name: ActivityPubFollowRequesterJob, queue: apFollowRequester, request-id: D870E4CB-E308-471D-A90B-4A0A92C90B47]
vernissage-api  | [ INFO ] GET /api/v1/users/@z428@loma.ml [request-id: 0D02071B-DF5C-4846-B888-D953A9031D12]
vernissage-api  | [ INFO ] Dequeing and running job [attempt: 1, job-id: FC8A0C41-5F54-45AA-BBD2-09865B6944CE, job-name: ActivityPubFollowRequesterJob, queue: apFollowRequester, retries-left: 0]
vernissage-api  | [ INFO ] ActivityPubFollowRequesterJob dequeued job. Entity data (source: 'https://grzeca.eu/actors/mariusz', target: 'https://loma.ml/profile/z428', type: 'follow'). [job_id: FC8A0C41-5F54-45AA-BBD2-09865B6944CE, queue: apFollowRequester]
```

It looks like something is happening, but the follow request remains in a "pending" state, and the other side never receives a notification that I've followed them.

**Comment by mgrzeca** [comment]
On my previous instance back in April, after the fix for issue #32, there were still some minor issues with Pixelfed instances. The first follow attempt wouldn’t work—I had to click "unfollow" and then "follow" again, and that would establish the connection properly.

However, this trick no longer works in the current situation.

**Comment by mczachurski** [comment]
Could you please verify the latest fix?

I resolved the issue with downloading the account from Fredrica and confirmed that I can now follow users from Mastodon, Pixelfed (tested with pixelfed.social and pixelfed.de), and Fredrica (e.g., loma.ml). However, there remains an issue with searching for and following users from Misskey, which has been reported here: https://github.com/VernissageApp/VernissageWeb/issues/114.

**Comment by mgrzeca** [comment]
No, the latest fix hasn’t resolved the issue. The behavior is still the same.

**Comment by mczachurski** [comment]
I tested with https://frederica.word, and it appears that the default behavior there requires users on Fredrica to accept follow requests:

![image](https://github.com/user-attachments/assets/a635c009-796c-4282-bedf-586c6e8bc568)

After the user accepts the request, the status in Vernissage updates.

**Comment by mgrzeca** [comment]
I tried following the same profiles from the official instance, and it looks like you were right regarding Friendica. However, the other profiles are working correctly.

As for my instance, it seems that the problem might be related to the fact that this domain has previously hosted Pixelfed, Mastodon, and Vernissage instances. While the transition from Pixelfed to Mastodon didn’t cause any issues, and the initial move from Mastodon to Vernissage in April was also smooth, it seems that launching a new Vernissage instance on the same domain now is problematic for Pixelfed, and it doesn’t want to cooperate.

I think I may have to use another one of my domains, or maybe buy a new one, because this one seems to be "burnt." And honestly, I don’t have the energy to deal with Pixelfed’s maintainer again—it’s too much for me to handle right now, I'd rather kill myself.

**Comment by mczachurski** [comment]
In that case, I will close this issue. Hopefully, it will now function correctly
