### ISSUE TITLE
s3Address setting ignored

### ISSUE THREAD

**Issue by mgrzeca** [VernissageApp/VernissageServer#27]
The 's3Address' configuration option seems to be ignored.
The API is attempting to connect to AWS instead of my self-hosted MinIO.

**Comment by mczachurski** [comment]
So maybe you still have that variable `s3Region` in the `app settings.json` file. You should remove it, when you use different S3 provider then AWS.

**Comment by mgrzeca** [comment]
Sure I do. If I delete the region, I get a different error:

`[ WARNING ] AuthorizationHeaderMalformed: The authorization header is malformed; the region is wrong; expecting 'eu-central-1'.`

 But at least tcpdump suggests that the response is from my MinIO.

**Comment by mgrzeca** [comment]
Okay, that was easy to fix...
