### ISSUE TITLE
The SMTP implementation not compliant with RFC 5321

### ISSUE THREAD

**Issue by mgrzeca** [VernissageApp/VernissageServer#28]
VernissageServer is unable to send emails through self-hosted mailcow-dockerized. In the logs, the following appears:

`vernissage-api  | [ ERROR ] Job failed, retrying... SmtpError(message: "521 5.5.2 moo.jmdi.pl Error: bare <LF> received") [job_id: E23071DA-43B1-48F6-BA91-4794B6B27A6A, job_name: EmailJob, queue: emails]`

This indicates that the SMTP client is sending a line terminated with LF, violating the RFC 5321 requirement that lines must end with CRLF.

**Comment by mczachurski** [comment]
Yesterday I did small change in the SMTP library and new docker image is available (develop tag). Unfortunately I didn't find any mailcow server to test this change. Can you update your instance and test it? If it is not working still, then do you know where I can test or do you have good instructions how to run it with local docker?

**Comment by mgrzeca** [comment]
The change didn't change a thing :) Same old glitch persists. You don't need mailcow for testing; any Postfix MTA version >= 3.6 will do (below 3.9, you gotta enable smtpd_forbid_bare_newline in config, it's on by default in 3.9+). Setting up mailcow in Docker is pretty straightforward if you're familiar with configuring MTAs and DNS mail-related records. It's well-documented here: https://docs.mailcow.email/getstarted/install/. However, it might be time-consuming if you're not experienced with it. Just to be safe, I'll create a test email account for you on my server.

**Comment by mgrzeca** [comment]
[244952c](https://github.com/VernissageApp/VernissageServer/commit/244952c1e6648fdfea1805bd552621ec0cb88255) seems to be solving the issue, thanks!
