### ISSUE TITLE
Problems with federation

### ISSUE THREAD

**Issue by mgrzeca** [VernissageApp/VernissageServer#32]
I'm unable to follow certain users. Honestly, I can only follow users from a different Vernissage instance. Below are examples:

Attempting to search for @tokyocameraclub@mstdn.tokyocameraclub.com results in an error:

`[ WARNING ] ActivityPub profile URL cannot be downloaded: 'https://mstdn.tokyocameraclub.com'. [request-id: 942561A5-542F-41EA-AA33-A2F39DE69605]`

Attempting to search for @monoscope@photog.social

```
vernissage-api  | [ INFO ] GET /api/v1/search [request-id: A51B6FD9-EBDB-4D3A-9D49-1C208B9BBEA7]
vernissage-api  | [ ERROR ] Error during download profile: 'https://photog.social/users/monoscope'. Error: notSuccessResponse(<HTTPURLResponse 0x00007f52982de200> { URL: https://photog.social/users/monoscope }{ status: 401, headers {
vernissage-api  |    "Cache-Control" = private, no-store;
vernissage-api  |    "Connection" = keep-alive;
vernissage-api  |    "Content-Security-Policy" = base-uri 'none'; default-src 'none'; frame-ancestors 'none'; font-src 'self' https://photog.social; img-src 'self' https: data: blob: https://photog.social; style-src 'self' https://photog.social 'nonce-JREv56iK5vCwJPiQ1lNpiA=='; media-src 'self' https: data: https://photog.social; frame-src 'self' https:; manifest-src 'self' https://photog.social; form-action 'self'; child-src 'self' blob: https://photog.social; worker-src 'self' blob: https://photog.social; connect-src 'self' data: blob: https://photog.social https://cdn.masto.host wss://photog.social; script-src 'self' https://photog.social 'wasm-unsafe-eval';
vernissage-api  |    "Content-Type" = "application/json; charset=utf-8";
vernissage-api  |    "Date" = Tue, 09 Apr 2024 21:20:03 GMT;
vernissage-api  |    "Referrer-Policy" = same-origin;
vernissage-api  |    "Server" = Mastodon;
vernissage-api  |    "Strict-Transport-Security" = max-age=63072000; includeSubDomains;
vernissage-api  |    "Transfer-Encoding" = chunked;
vernissage-api  |    "Vary" = Accept, Accept-Language, Cookie, Signature, Origin;
vernissage-api  |    "X-Content-Type-Options" = nosniff;
vernissage-api  |    "X-Frame-Options" = DENY;
vernissage-api  |    "X-Request-Id" = 5d1087cd-df6b-4212-ad97-84a62897c35a;
vernissage-api  |    "X-Runtime" = 0.009382;
vernissage-api  |    "X-XSS-Protection" = 0;
vernissage-api  | } }).
vernissage-api  | [ WARNING ] ActivityPub profile cannot be downloaded: 'https://photog.social/users/monoscope'. [request-id: A51B6FD9-EBDB-4D3A-9D49-1C208B9BBEA7]
```

I can search for Pixelfed users, but I can't follow them. For instance, trying to follow @chaospixel@pixelfed.social results in:

```
vernissage-api  | [ INFO ] POST /api/v1/users/@chaospixel@pixelfed.social/follow [request-id: 17B12A5C-67AE-481B-84BF-1BA8B066664A]
vernissage-api  | [ INFO ] Dispatched queue job [job_id: 8D458C65-5AE6-47D6-8B58-63FE932CED7F, job_name: ActivityPubFollowRequesterJob, queue: apFollowRequester, request-id: 17B12A5C-67AE-481B-84BF-1BA8B066664A]
vernissage-api  | [ INFO ] Dequeueing job [job_id: 8D458C65-5AE6-47D6-8B58-63FE932CED7F, job_name: ActivityPubFollowRequesterJob, queue: apFollowRequester]
vernissage-api  | [ INFO ] ActivityPubFollowRequesterJob dequeued job. Entity data (source: 'https://grzeca.eu/actors/mariusz', target: 'https://pixelfed.social/users/chaospixel', type: 'follow'). [job_id: 8D458C65-5AE6-47D6-8B58-63FE932CED7F]
```

Nothing else happens; the user remains with a pending follow request.

**Comment by mczachurski** [comment]
I've did a lot of improvements in federation. Hopefully I've fixed most of the issues. I have still issue with @tokyocameraclub@mstdn.tokyocameraclub.com profile - but it seems like an issue with network. Can you verify my fixes?

**Comment by mgrzeca** [comment]
It seems like the previous issues are no longer happening. I can both search and follow without any problems. Great job!

**Comment by mgrzeca** [comment]
However, I notice one regression (?). Previously, my domain was used by a test instance of Mastodon. I was following several hundred accounts from various instances. I deleted my account and after some time, I also deleted the instance. Currently, my global timeline is filled with posts from accounts I was following on my Mastodon. Should VernissageServer accept such posts?

**Comment by mczachurski** [comment]
Great that issues has been fixes. Your last issue can be tricky. It seems, that other mastodon instances remember somehow your account (and follows) and they are sending statuses to your instance/domain still when someone who you followed is creating a new post.

> Should VernissageServer accept such posts?
This is a very good question. Theoretically I can check (before creating the new post from ActivityPub) if anyone in the instance is still following the user who create/boost the status. However I'm not sure if that is expected behaviour and if I will not broke something different 🤔. 

As I understood these posts are not added to your local/private timeline only for global timeline?

**Comment by mczachurski** [comment]
I think I will add checks if author of new status/boost is followed by anyone on the instance.
This should prevent that if a server is malicious and specifically sends out messages that no one wants.

**Comment by mczachurski** [comment]
Fixed in new version. Thanks a lot for your help 👍.
