### ISSUE TITLE
Missing comments.

### ISSUE THREAD

**Issue by mgrzeca** [VernissageApp/VernissageServer#53]
Isn't this one of the unforeseen consequences of commit [12fcb5f](https://github.com/VernissageApp/VernissageServer/commit/12fcb5f797f3bbbc777f0e61c91e51d6d08b3ee4) that you were concerned about? I've looked through some statuses with comments and compared how they appear on other servers. It seems that on my instance, there are only comments from people I follow. Below is an example post - Kaja is a good candidate for diagnosing these kinds of issues, because there are usually plenty of comments under her statuses :)

https://photog.social/@Kaya/112291319346378579
https://grzeca.eu/statuses/7359123473228472321

 For instance, I'm missing a comment from @Apothekla@social.cologne because she's not on my follow list.

**Comment by mczachurski** [comment]
During adding the comment I always get user from database (and some of remote users doesn't exists in local database). Now I'm getting user from local database, but if it's not exists or the profile is older then few 24 hours, then it's downloaded from remote server and saved in local database.

I'm adding to database (local instance) only comments if in the database we have parent status/comment.
